#!/bin/bash

echo -e "\033[1;31mATENÇÃO!!\033[0m"
echo " "
echo -e "\033[1;33mEsta senha será utilizada para iniciar sessão em seu servidor \033[0m"
echo " "
echo -ne "\033[1;32mDIGITE UMA NOVA SENHA\033[1;37m: "; read senha
[[ -z "$senha" ]] && {
echo -e "\n\033[1;31mSENHA INVÁLIDA !\033[0m"
exit 0
}
echo "root:$senha" | chpasswd
sleep 1s
echo -e "\n\033[1;32mSENHA ALTERADA COM SUCESSO!\033[0m"
sleep 3s
cd
clear

